### ISSUE TITLE
עברית מוצגת בכיוון ההפוך

### ISSUE THREAD

**Issue by moriel5** [yehoshuapw/InfiniTime#1]
אני מאמין שכנראה זה לא משהו שניתן לתקן בשלב הנוכחי, אך בדקתי את התמיכה בעברית, ומסתבר שהתרעות מוצגות משמאל לימין, גם אם הן בעברית.

**Comment by yehoshuapw** [comment]
לו זה היה נכון, אז היה (די) חסר פואנטה שהfork הזה יהיה קיים, ובמשך זמן קימו מישהו כבר היה מעלה את הנקודה הזו.

מאחר שזה כבר סגור, קשה למצוא את זה, אבל אכן: https://github.com/InfiniTimeOrg/InfiniTime/pull/311

בקצרה, בGadgetBridge יש פיצר שהופך אתת הכיוון.

**Comment by yehoshuapw** [comment]
הוסף טיפה תיעוד רלוונטי לREADME.md

**Comment by moriel5** [comment]
אכן, איכשהו שכחתי כליל מאפשרות זו.
אשריך, תודה רבה לך.
