### ISSUE TITLE
פישוט הפורק

### ISSUE THREAD

**Issue by tom-programming** [yehoshuapw/InfiniTime#3]
### Verification

- [X] I searched for similar feature request and found none was relevant.

### Pitch us your idea!

פישוט הפורק

### Description

אם רק מפעילים את LV_USE_BIDI לקשוחה עצמה תהיה תמיכה לטקסט דו-כיווני. זה פותר את הצורך בתלות בgadgetbridge , אבל אולי זה ידרוש יותר זכרון

בכל זאת התמיכה לטקסט בעברית היא יותר טובה (היא עובדת גם לדוגמא לכותרת של השיר שמתנגן - בתוכנת מוזיקה - ולא רק להתראות)

בסך הכל התיקונים היחידים שצריך לעשות על הקוד הרשמי הם

- הפעלת LV_USE_BIDI ב lv_conf.h
- הוספת הגופן בעברית
- הוספת הסימנים בfonts.json

מדובר על 3 שינויים בלבד בשלב הזה אז ייתכן שקיימת דרך פשוטה יותר מאשר לתחזק פורק שלם - ובכל זאת להיות ידידותיים למי שנכנס לזה בפעם הראשונה

הייתי מציע בנוסף לשינוי של LV_USE_BIDI להמיר את הפורק הזה לרפוזיטורי שפשוט שולף את הרפוזיטורי המקורי כ״תת-רפו״ ומוסיף את התיקונים בצורה של סקריפט אחד. אלא אם כן רוצים לעשות משהו הרבה יותר מקיף (תרגום של כל התוכנה, לוח שנה עברי...) זה כל מה שצריך עכשיו

**Comment by yehoshuapw** [comment]
bidi version:

```
post build steps for pinetime-mcuboot-app-1.11.0
   text    data     bss     dec     hex filename
 422432    1304   54060  477796   74a64 pinetime-mcuboot-app-1.11.0.out
```

normal version:

```
post build steps for pinetime-mcuboot-app-1.11.0
   text    data     bss     dec     hex filename
 419768    1304   54028  475100   73fdc pinetime-mcuboot-app-1.11.0.out
```

so text takes another 2664 which is not a small amount.
it does work however, so (in case someone wants a dfu with it. not on android?): https://github.com/yehoshuapw/InfiniTime/actions/runs/3740349692 (more directly: https://github.com/yehoshuapw/InfiniTime/suites/9968249953/artifacts/483220214)

about having inside the main repo, the decision there was not to have any "optional" features or such yet, so for now a fork does the job. moving the extra font to the FS and knowing when to read it (maybe some setting even) can be accepted - but I don't have time for that at the moment.
