### ISSUE TITLE
Instruction for compiling

### ISSUE THREAD

**Issue by gergesh** [yehoshuapw/InfiniTime#4]
### Verification

- [X] I searched for similar issues (including closed issues) and found none was relevant.

### Introduce the issue

Hi!
Seeing as the hebrew-support branch has no commits on top of upstream:main, does that mean that adding Hebrew support is as simple as enabling some options or adding compile-time flags?
If so, instructions for the procedure could be very useful to those looking to build the recent firmware with Hebrew fonts added (such as myself).
Thanks for all of the hard work!

**Comment by yehoshuapw** [comment]
no, it means I forgot to finish the cherry-pick conflicts before pushing..

**Comment by gergesh** [comment]
Thank you! I'd like to link this here to make it easier for people to find in the future - releases are just GitHub build artifacts, and can be downloaded from https://github.com/yehoshuapw/InfiniTime/actions
